### ISSUE TITLE
На проверку

### ISSUE THREAD

**Issue by akaikiberken** [systemo-biz/test#35]
Проверьте, будьте добры
ссылка http://mtzforsyst.esy.es/

**Comment by yumashev** [comment]
хорошо.
только зачем и как сломан шрифт сайта?
http://monosnap.com/image/ZFxODZUnoskmzXUwTw5VkIN60pf1SH

**Comment by akaikiberken** [comment]
в теме встроены общие настройки - шрифт поменял на Trebuchet. 
Мне понравился 
Восстановил дефолтные

**Comment by yumashev** [comment]
Шрифты с засечками были придуманы для печати на бумаге чтобы бороться с растеканием чернил.
Некоторые дизайнеры их используют для типографики под старину в заголовках. Если умело это применять то смотрится красиво.
Мне сложно придумать смысл использования шрифта с засечками как основного на сайте.
Но мб я чего то не вижу? Поделись своим видением.

Дизайн и изменения должны быть осмысленны и нести какие то цели и соответствовать понятным требованиям. Менять что то просто так и не понимая смысла - опасное занятие. Можно дров наломать.
Ну это к слову о дизайне, принципах архитектуры и философии.

В остальном ок. Запиши тут email и перейдем к второму этапу :)

**Comment by akaikiberken** [comment]
shumov.vlad@gmail.com
