### ISSUE TITLE
Вопрос по 2.3

### ISSUE THREAD

**Issue by philatm** [systemo-biz/test#39]
Здравствуйте. Пытаюсь сделать пункт 2.3 и пишу такой код, в копии файла archive.php
<?php while ( have_posts() ) : the_post(); ?>

				<?php
					echo get_the_term_list(get_the_ID(), 'genres', 'Жанры: ', ', ') . '<br>';
					get_template_part( 'content', get_post_format() );
					echo get_the_term_list($post->ID, 'countries', 'Страны: ', ', ') . '<br>';
					echo 'Стоимость: ' . get_post_meta(get_the_ID(), 'price', true) . '<br>';
				?>

			<?php endwhile; ?>
Но дело в том, что жанр он выводит сверху записи, а страну и стоимость тоже сверху только к следующей записи http://philatm.esy.es/wp/?post_type=movie. Что я делаю не так? Заранее благодарю

**Comment by yumashev** [comment]
1. Пчм правится archive.php? Статья надо читать внимательней. Это раз. Исправить.
2. Два - нужен полный код. Всего файла. Без контекста сложно понять что это такое и как оно работает.

**Comment by philatm** [comment]
Я просто скопировал файл archives.php с родительской темы. Как его назвать? archives-movies? И в цикле добавил вывод:
<?php
/**
 * The template for displaying Archive pages.
 *
 * Learn more: http://codex.wordpress.org/Template_Hierarchy
 *
 * @package unite
 */

get_header(); ?>

	<section id="primary" class="content-area col-sm-12 col-md-8 <?php echo of_get_option( 'site_layout' ); ?>">
		<main id="main" class="site-main" role="main">

		<?php if ( have_posts() ) : ?>

			<header class="page-header">
				<h1 class="page-title">
					<?php
						if ( is_category() ) :
							single_cat_title();

						elseif ( is_tag() ) :
							single_tag_title();

						elseif ( is_author() ) :
							printf( __( 'Author: %s', 'unite' ), '<span class="vcard">' . get_the_author() . '</span>' );

						elseif ( is_day() ) :
							printf( __( 'Day: %s', 'unite' ), '<span>' . get_the_date() . '</span>' );

						elseif ( is_month() ) :
							printf( __( 'Month: %s', 'unite' ), '<span>' . get_the_date( _x( 'F Y', 'monthly archives date format', 'unite' ) ) . '</span>' );

						elseif ( is_year() ) :
							printf( __( 'Year: %s', 'unite' ), '<span>' . get_the_date( _x( 'Y', 'yearly archives date format', 'unite' ) ) . '</span>' );

						elseif ( is_tax( 'post_format', 'post-format-aside' ) ) :
							_e( 'Asides', 'unite' );

						elseif ( is_tax( 'post_format', 'post-format-gallery' ) ) :
							_e( 'Galleries', 'unite');

						elseif ( is_tax( 'post_format', 'post-format-image' ) ) :
							_e( 'Images', 'unite');

						elseif ( is_tax( 'post_format', 'post-format-video' ) ) :
							_e( 'Videos', 'unite' );

						elseif ( is_tax( 'post_format', 'post-format-quote' ) ) :
							_e( 'Quotes', 'unite' );

						elseif ( is_tax( 'post_format', 'post-format-link' ) ) :
							_e( 'Links', 'unite' );

						elseif ( is_tax( 'post_format', 'post-format-status' ) ) :
							_e( 'Statuses', 'unite' );

						elseif ( is_tax( 'post_format', 'post-format-audio' ) ) :
							_e( 'Audios', 'unite' );

						elseif ( is_tax( 'post_format', 'post-format-chat' ) ) :
							_e( 'Chats', 'unite' );

						else :
							_e( 'Archives', 'unite' );

						endif;
					?>
				</h1>
				<?php
					// Show an optional term description.
					$term_description = term_description();
					if ( ! empty( $term_description ) ) :
						printf( '<div class="taxonomy-description">%s</div>', $term_description );
					endif;
				?>
			</header>

			<?php /* Start the Loop */ ?>
			<?php while ( have_posts() ) : the_post(); ?>

				<?php
					/* Include the Post-Format-specific template for the content.
					 * If you want to override this in a child theme, then include a file
					 * called content-___.php (where ___ is the Post Format name) and that will be used instead.
					 */
					
					echo get_the_term_list($post->ID, 'genres', 'Жанры: ', ', ') . '<br>';
					get_template_part( 'content', get_post_format() );
					
					echo get_the_term_list($post->ID, 'countries', 'Страны: ', ', ') . '<br>';
					echo 'Стоимость: ' . get_post_meta(get_the_ID(), 'price', true) . '<br>';
				?>
			<?php endwhile; ?>
			<?php unite_paging_nav(); ?>

		<?php else : ?>

			<?php get_template_part( 'content', 'none' ); ?>


		<?php endif; ?>

		</main>
	</section>

<?php get_sidebar(); ?>
<?php get_footer(); ?>

**Comment by yumashev** [comment]
1. Я не знаю как он должен называться. Это зависит от параметров добавления типа поста. А это знаешь только ты. Для того чтобы это понять, надо внимательно прочитать статью. Если столь простой вопрос вызывает затруднения, при том что дана статья, то дальше нет смысла тратить время. Далее будут задачи кратно сложнее и готовых статей где все разжовано не будет. Можно попытаться еще раз прочитать статью. Внимательно.
2. для того чтобы показать код лучше использовать pastebin.com или выучить маркдаун синтаксис. В целом выглядит нормально. Но надо увидеть результат, а для этого надо с п. 1 разобраться.

**Comment by philatm** [comment]
Назвал файл archive-movie.php(так как запись имеет имя movie) Но ничего не поменялось: http://philatm.esy.es/wp/?post_type=movie. Вот код: http://pastebin.com/zVm5FMLw

**Comment by infected9k** [comment]
в archive-movie.php укажите content-movie, создайте его и с ним работайте

**Comment by yumashev** [comment]
ты засунул жанры выше секции, а остальное ниже.
так и выводится. 
как сделал так и получил.

если хочешь изменить то что внутри секции, то надо или править соответствующий шаблон или код того шаблона перетащить в этот и тут поправить как надо.

**Comment by yumashev** [comment]
для того чтобы найти нужный шаблон, стоит знать логику функции get_template_part
она легко находится в Яндексе.
поняв ее, ты поймешь где лежит нужный шаблон.

**Comment by philatm** [comment]
Всем спасибо. Сделал http://philatm.esy.es/wp/?post_type=movie

**Comment by yumashev** [comment]
ок, молодец!
почту в студию

**Comment by philatm** [comment]
philamooh@gmail.com

**Comment by philatm** [comment]
с
