### ISSUE TITLE
Отчет о тестовом задании

### ISSUE THREAD

**Issue by tyllo** [systemo-biz/test#51]
[![](http://bit.ly/1JU72vj)](http://take.ms/kz8qW)

[Тестовое задание](http://tyllo.pe.hu/)

[**Код плагина**](https://gist.github.com/tyllo/c0074943053e1ea1b9e9)

**Comment by yumashev** [comment]
Хорошо. Заметно умение превосходить ожидания и делать чуть больше. Это очень хорошо.
Плохо то что код HTML внутри php пишется. Это коряво. Читаемость падает. Верстальшику потом тяжко будет это разгребать.
Умеешь писать более читаемый код? Например через механизм ob_start?

Нужен ответ на этот вопрос, а лучше сразу демонстрация навыка.

Ну и нужна почта для продолжения общения.

**Comment by yumashev** [comment]
Вру. Вижу конструкцию EOF. В общем то это даже лучше чем ob_start. Потому просто жду email )

**Comment by tyllo** [comment]
gmtyllo@gmail.com
