### ISSUE TITLE
Задание на проверку

### ISSUE THREAD

**Issue by stas9005** [systemo-biz/test#52]
1) Сайт http://moviemovie.96.lt/
2) Плагин http://pastebin.com/d0fcYWqt
3) Скриншот https://www.dropbox.com/s/qu6ww9pdrdihuku/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-05-04%2019.07.46.png?dl=0

**Comment by yumashev** [comment]
Отличная работа!
Напиши свою почту тут. Для дальнейшего общения.

**Comment by stas9005** [comment]
stas9005@gmail.com
