### ISSUE TITLE
Тестовое задание: Выполнено!

### ISSUE THREAD

**Issue by deeem** [systemo-biz/test#53]
Тестовое задание довольно подробно и понятно, поэтому вопросов не возникало, всё решалось в гугле.

Само задание предлагает сделать каталог фильмов, он получается хоть и простой, но довольно завершённый. Я подумал, что не плохо бы завернуть весь его функционал в один плагин и не использовать дополнительные, пусть и хорошие, но сторонние плагины. В результате, получилась работа по "мотивам" тестового задания. Надеюсь, Вас это устроит. Но если нужно было сделать всё именно как в задании, то переделаю.

Ссылки:
* http://deeem.esy.es/  - сам сайт, на главной странице которого шорткодом выведены 5 последних фильмов
* http://deeem.esy.es/movies/ - фильмы выведены сеткой, с шириной 4/3/2/1 фильм в зависимости от ширины экрана
* http://deeem.esy.es/movies/insurgent/ - подробная информация о фильме
* https://github.com/deeem/systemobiztest2 - сам плагин с описанием (или тут нельзя размещать ссылки на код?)

**Comment by yumashev** [comment]
Оч круто!
Мыло надо написать тут. Чтобы двинуться дальше.

**Comment by deeem** [comment]
maksimnovgorodov85@gmail.com
