### ISSUE TITLE
Задание на проверку

### ISSUE THREAD

**Issue by web2033** [systemo-biz/test#60]
Привет, проверьте, что получилось
Сайт: http://wpwp.zz.mu/
Сниппеты кода и скриншоты: http://wpwp.zz.mu/zapis-s-kodom/

**Comment by avto-motors54** [comment]
Как сделать для темы дочку на http://www.hostinger.ru/ ?????????

**Comment by web2033** [comment]
@avto-motors54 привет, там статья-подсказка указана https://wpmag.ru/2013/dochernie-temy-wordpress/
Информация на оф. сайте - https://codex.wordpress.org/%D0%94%D0%BE%D1%87%D0%B5%D1%80%D0%BD%D0%B8%D0%B5_%D1%82%D0%B5%D0%BC%D1%8B - хотя там устаревшая версия перевода, в первоисточнике на англ. языке немного по-другому делается, в плане использования import, подробнее тут http://web2033.com/child-wordpress-themes-import/

Хостингер тут не имеет отношения к делу, дочерние темы создаются на всех хостингах одинаково. 
P.S. Я тут такой же участник стажировки как и вы)

**Comment by avto-motors54** [comment]
спасибо, буду пробывать ...

**Comment by yumashev** [comment]
1. Видно что старался. Даже перестарался :)
2. Когда речь идет о том чтобы разместить ссылку на Pastebin или Monosnap - это и нужно сделать. Тут цель проверить умеешь ты общаться на форумах или нет. Можешь ты показать код или снимок в ветке форума или нет. Сейчас получается что нет. Это надо исправить. Не стоит размещать эти материалы на своем сайте.
3. Зачем сломал стили темы? Показать что умеешь опции править? Получилось плохо. В базовых стилях сайт смотрится лучше. Это лишнее. А делать лишнее - всегда очень опасно и результат вегда будет хуже. Нужно не только уметь что то делать хорошо, но и уметь не делать лишнего. Это называется "неделание". Неделание очень важно как и делание. И судя по результату с этим у тебя проблемы :)

В остальном все ок. Черкни почту.

**Comment by web2033** [comment]
@yumashev web2033@gmail.com

**Comment by web2033** [comment]
@yumashev не в спаме мое письмо? После 6-го числа ответа не было...
