### ISSUE TITLE
Тестовое

### ISSUE THREAD

**Issue by Zalki-Lab** [systemo-biz/test#61]
1.Одиночная страница http://luger-luger.rhcloud.com/?cinema=the-big-bang-theory
2.Вывод всех custom posts http://luger-luger.rhcloud.com/?post_type=cinema
3.С bootstrap и иконками http://luger-luger.rhcloud.com/?page_id=28
4.Код плагина: http://pastebin.com/pJ3b8rti http://pastebin.com/APY5kza3

**Comment by yumashev** [comment]
пункт 4 крайне усложнен.
это правильная метода если ты пишешь замудренный плагин из 100 000 строк кода.
а тут простая задача на 10 строк. зачем так усложнять?
что мешало сделать просто через функцию?
это обеспечило бы удобство, читаемость и простоту правки кода.
в малых задачах это более оптимальная метода.
то что сделал ты - более сложный метод, и его применение понятно в сложных плагинах.
но не понятно зачем так было сделано тут?
можешь свою точку зрения написать?

**Comment by yumashev** [comment]
пункт 4.3 не выполнен

**Comment by Zalki-Lab** [comment]
Ну ты сам ответил на свой вопрос, это было сделано с перспективой на расширение. Но через функцию тоже можно

**Comment by yumashev** [comment]
Это называется "нарушение принципа бритвы Оккама". Примерно тоже самое как если бы в поход на 2 дня, ты бы взял 3 чемодана вещей. На всякий случай.
Беда в том что случай этот маловероятен, а тащить их за собой - проблема.
Очень важно уметь решать задачи достаточными методами, без избыточных.
А сложные методы использовать лишь при необходимости. Отдавая предпочтения простым решениям там где это возможно.

В остальном все ок. Черкни свой email

**Comment by Zalki-Lab** [comment]
Согласен, но в задаче не было сказано, что нужно сделать это как можно проще. Без вариантов дальнейшего расширения. Ну и хотелось показать, что есть умение работать не только в процедурном стиле. Сейчас отправлю письмо на твой ящик с темой Zalki-Lab
