### ISSUE TITLE
Тестовое задание

### ISSUE THREAD

**Issue by sashapenkova** [systemo-biz/test#62]
А в задании 5.3 пул реквест можно как-то сделать через sourcetree? или нужно его делать через fork и pull request на githube?

Сайт - http://www.moviesinfo.esy.es/
Код плагина - http://pastebin.com/BRX1gfqh
Снимок шаблона - http://take.ms/Iox0X

**Comment by yumashev** [comment]
>> А в задании 5.3 пул реквест можно как-то сделать через sourcetree? или нужно его делать через fork и pull request на githube?

если дать доступ то можно. но не получится на этапе теста. потому стандартным для GitHub является метод fork + pull

**Comment by yumashev** [comment]
в остальном все ок. дай свой email

**Comment by sashapenkova** [comment]
greipfruit@gmail.com
