### ISSUE TITLE
[тестовое задание] Вопрос

### ISSUE THREAD

**Issue by aopletaev** [systemo-biz/test#63]
Здравствуйте!
С WP ранее не работал, да и в php по сути начинающий, поэтому задание дается не без труда...
Застопорился на этапе вывода дополнительных полей по фильму в ленте фильмов с использованием правки шаблона. 
Как я понял нужно из файла archive.php создать файл archive-movie.php, далее в нем прописывать вывод  дополнительных полей.
Я нашел место в коде где работает цикл с выводом всех постов(фильмов), внутри цикла я могу получить данные поля конкретного поста, например дату премьеры:

   $post_id = get_the_ID();
   $premiere_date = get_post_meta($post_id, 'premiere_date', true );

Не получается вывести эти поля в нужном месте(под описанием фильма, как организованно на странице фильма).
Как я логически себе это представляю: все данные о фильме содержатся в строковой переменной, логично было бы оператором .(точка) склеить информацию о посте и полученные мной дополнительные данные. По аналогии как я сделал с хуками:

   $content = $content.$dop_data;

Но не тут то было...
Подскажите, пожалуйста,  в какую сторону копать? И вообще правильно ли я понял принцип?

**Comment by aopletaev** [comment]
ах да, вот сам проект http://oplfilms.esy.es/movie/

**Comment by aopletaev** [comment]
дорылся до того, что залез в файл /public_html/wp-content/themes/unite/content.php там вставил код вывода, куда более приглядная вещь:
![test_films](https://cloud.githubusercontent.com/assets/13112305/8428362/9f8c22a6-1f37-11e5-958c-a02bb67adc08.JPG)
Но как я понимаю, не есть хорошо, изменять стандартные файлы WP? а может я вообще не в ту степь полез?

**Comment by web2033** [comment]
@aopletaev дочернюю тему создай сперва и там уже правки вноси

**Comment by aopletaev** [comment]
@web2033, это мне понятно, дочку я создал...
В таком случае, когда я из файла archive.php создаю файл archive-movie.php для того, чтобы прописать в нем код для вывода доп полей(жанр, страна, дата премьеры стоимость сеанса). Вновь созданный файл(archive-movie.php) я должен положить в каталог с дочерней темой?
![123243](https://cloud.githubusercontent.com/assets/13112305/8430442/275e750e-1f4b-11e5-90b5-31611d81b769.JPG)

**Comment by web2033** [comment]
@aopletaev да, все создаваемые файлы размещаются в дочерней теме, а из родительской берутся образцы нужных шаблонов

**Comment by aopletaev** [comment]
@web2033, спасибо за наставление!
Тогда вернусь к основному вопросу - правильно ли то, что я выбрал файл content.php для реализации в нем вывода? Если да то, вроде, все получается, за исключением того, что все выводится заглавными буквами и цвет серый...в таком случае остается это подправить стилями??

**Comment by aopletaev** [comment]
ну вроде вырулил...
прописал вывод в файле content.php, за пределами стилей, который действовали на отображение доп полей. Вот что получилось:
![432](https://cloud.githubusercontent.com/assets/13112305/8452667/5f979318-2006-11e5-84d3-03c2cd20ff17.JPG)
НО, пока не знаю как вывести дату в правильном формате?

**Comment by web2033** [comment]
@aopletaev в настроить в плагине ACF соотв. поле

**Comment by aopletaev** [comment]
Снова не могу разобраться...пишу шорткод для вывода 5 последних постов:

   function last_five_posts()
   {
	$posts = get_posts('numberposts=5&post_type=movie');
        //var_dump($posts);
	
	foreach($posts as $post)
	{
	   setup_postdata($post);
    	   the_title();
	}
	wp_reset_postdata();
   }
add_shortcode ('lfp','last_five_posts');

В итоге у меня выводит 5 раз "Привет мир!", хотя я ожидаю увидеть пять разных заголовков фильмов(Форест Гамп, Интерстеллар и тд). Я ведь указываю post_type=movie и когда var_dump($posts) делаю, там все мои 5 фильмов внутри. А кода вывожу - выводит "Привет мир!".
Не могу понять где я не прав?
http://oplfilms.esy.es/

**Comment by aopletaev** [comment]
Делаю шорт код для вывода последних 5 фильмов:

function last_five_posts()
{
	$posts = get_posts('numberposts=5&post_type=movie');	
	foreach ($posts as $post) 
	{
		echo $post->post_title.'<br>'.$post->post_content.'<br><br>';
	}
}
add_shortcode ('lfp','last_five_posts');

Для начала пробую ввести заголовок и описание фильма. Да, получается вывести заголовок и описание последних пяти фильмов, НО данные эти выводятся как бы в теле одного поста. Вот по ссылке понятно будет о чем речь http://oplfilms.esy.es/.
Пока не могу понять, почему так?
я же хочу, что бы было, не так что в дном посте пять заголовков.описаний, а каждый пост со своим заголовком.описанием...ну думаю понятно объяснил.

**Comment by aopletaev** [comment]
Кажется, со всем справился.
