### ISSUE TITLE
Вопросы по тестовому заданию

### ISSUE THREAD

**Issue by Lardo1980** [systemo-biz/test#64]
Установил ACF и создал группу полей "Фильм". Как привязать её к ранее созданному типу записи ?

**Comment by yumashev** [comment]
Там должен быть блок, где можно указать сущности к которым привязываться. Одна из них зовется Тип записи. Там выбрать фильм и эти поля будут привязаны к типу поста Фильм.

**Comment by Lardo1980** [comment]
Пытаюсь получить список термов таксономии текущего поста и результат пустой. В чём может быть проблема ?
$terms = wp_get_post_terms('country');
		foreach ( $terms as $term )
		{
		$m_info = $m_info." ".$term->name;
		}
		$m_info = $m_info."<br>";

**Comment by yumashev** [comment]
По куску кода сложно понять причину. Обмен кодом лучше делать через pastebin.com.
Нужен весь код, чтобы понимать алгоритм.

**Comment by yumashev** [comment]
Хотя тут и так видно. У этой функции 3 параметра http://wp-kama.ru/function/wp_get_post_terms
А ты только один даешь.

**Comment by Lardo1980** [comment]
Я так понимаю в дочерней теме надо кинуть файл archive-movie.php для создания шаблона вывода списка фильмов ? Не пойму что дальше делать.

**Comment by Lardo1980** [comment]
Вордпресс себя странно ведет. Создаю обычную страницу с некоторым текстом и жму "Просмотреть страницу" - пишет "Nothing found", со страницами, основанными на шаблонах таже проблема. В чем может быть дело ?

**Comment by Lardo1980** [comment]
С предыдущим вопросом разобрался. Теперь вопрос куда вставить сетку 2x2 из раздела с бутстрапом ? Надо ли чтобы на странице выводилось 4 фильма в такой сетке или же сетка для вывода каждого фильма ?

**Comment by yumashev** [comment]
сетка только для данных фильма. но если хочешь вытащиьт фильмы сеткой - то это по желанию.

**Comment by Lardo1980** [comment]
Как следует добавлять в меню страницу с полным списком фильмов ? Я создаю пустую страницу и шаблоном ей выбираю archive-movie, но при этом страница пустая. Список фильмов выводится только если я в archive-movie.php добавляю query_posts по типу поста.
