### ISSUE TITLE
[тестовое задание] Выполнил

### ISSUE THREAD

**Issue by aopletaev** [systemo-biz/test#65]
Здравствуйте!
Пожалуйста, проверьте тестовое задание.
Сайт: http://oplfilms.esy.es/
Код плагина: http://pastebin.com/N11iVev1#
Снимок кода шаблона с архивом фильмов: https://monosnap.com/file/IP5xvKu2c734DXipUX9skzV0vXzyOZ
Пул реквест с добавленным файлом отправил.
Жду вашего ответа :)

**Comment by yumashev** [comment]
echo использовать для HTML кода - печально.
Лучше HTML выводить за рамкам php скобок. Так лучше читается и правиться без лишних проблем.
Есть понимание как это исправить?

**Comment by aopletaev** [comment]
@yumashev попробую предложить такой вариант http://take.ms/40yNK

**Comment by yumashev** [comment]
так на много лучше. особенно когда HTML код большими кусками пишется. читается на порядок круче.
дай свою почту.

**Comment by aopletaev** [comment]
alxopltv1@gmail.com
