### ISSUE TITLE
Проверьте задание (исправил)

### ISSUE THREAD

**Issue by Lardo1980** [systemo-biz/test#66]
1 ссылка на каталог : http://mbase.esy.es
2 код плагина: http://pastebin.com/81Mf3Chk
3 снимок кода шаблона архива: http://monosnap.com/file/BZijHKgK73rN6NqPHPyewU4UPSRqCH
4 репозиторий склонировал, добавил файл и отправил pull реквест

**Comment by yumashev** [comment]
все фильмы вытащил через страницу http://mbase.esy.es/?page_id=36
это ошибка. надо выводить стадартным циклом.

**Comment by Lardo1980** [comment]
Я использовал архивную страницу, просто поправил шаблон как написано в заданиии.

**Comment by yumashev** [comment]
этот механизм не будет ловить стандартные параметры в адресе.
такое используется редко.
надо внимательней изучить иерархию шаблонов и сделать через правку шаблона архива под заданный тип поста.

**Comment by Lardo1980** [comment]
Переделал. Проверьте пожалуйста (в первой теме поменял ссылки).

**Comment by Lardo1980** [comment]
Я исправил.

**Comment by yumashev** [comment]
ок, хорошо, напиши почту

**Comment by Lardo1980** [comment]
zeltinpavel@gmail.com
