### ISSUE TITLE
Проверьте пожалуйста задание.

### ISSUE THREAD

**Issue by mrkcode** [systemo-biz/test#67]
Задание довольно интересное и не тяжелое. Я еще более детально углубился в WP. 

Ссылка на сайт: http://systemo-biz.niksma.ru
Ссылка на плагин: https://github.com/mrkcode/systemo-biz
Шаблон: http://i.imgur.com/XuyAYlh.png

**Comment by yumashev** [comment]
страница отдельного фильма не открывается http://monosnap.com/image/xa1tOk0DUVCO7WRCcJvbeCQDgPLzse

**Comment by mrkcode** [comment]
Извиняюсь, с хостингом прогадал) Все работает http://i.imgur.com/aGqptzB.jpg

**Comment by mrkcode** [comment]
Вот выложил на хостингер на всякий случай http://systemo-biz.esy.es/movies/%D0%BB%D0%BE%D0%B2%D1%83%D1%88%D0%BA%D0%B0-%D0%B4%D0%BB%D1%8F-%D0%BF%D1%80%D0%B8%D0%B7%D1%80%D0%B0%D0%BA%D0%BE%D0%B2/

**Comment by mrkcode** [comment]
Я так понимаю я не справился с заданием? Укажите хотя бы мои ошибки, пожалуйста.

**Comment by yumashev** [comment]
Все ок. Просто нет возможности каждый день писать. Черкни тут свой email

**Comment by mrkcode** [comment]
mrk.alterman@gmail.com
