### ISSUE TITLE
Пара вопросов по шорткоду через functions.php

### ISSUE THREAD

**Issue by acerus** [systemo-biz/test#70]
застопорился на правке functions.php для вывода шорткодов. Сначала все было весело, даже что-то он выводил но куда-то не туда понесло.

сейчас упорно не хочет запускать сайт ругаясь на неправильное окончание файла 
http://test.motivator-studio.ru/wp-admin/

как оно может быть неправильным, если там просто  ?> ???
на правильную кодировку и сохранение без BOM 100 раз проверил уже

**Comment by yumashev** [comment]
А снимок ошибки?

Ещё лучше убрать ?> от туда. Потому что ВП умеет так работать.
А если добавил то смотри чтобы после знака не было пробелов или переносов строки

**Comment by acerus** [comment]
убрал, вот и dreamweaver подчеркивает ошибку синтаксиса а я в упор не вижу ее 
http://take.ms/ha4ja
http://take.ms/e5Gqs

**Comment by yumashev** [comment]
add_shortcode выполняется за рамками функции для ее вызова.

function cheburek(){
...
}

add_shortcode(...);

А у тебя оно как то внутри получается.

**Comment by acerus** [comment]
Все, понял, это и было причиной.

По 3 пункту тогда вопрос - вывод блоков каким именно образом? шорткодом на отдельной странице? На странице категории? Или на свое усмотрение?

**Comment by yumashev** [comment]
Давай на своё усмотрение. А я если что удивлюсь.
