### ISSUE TITLE
Задание на проверку

### ISSUE THREAD

**Issue by amariq** [systemo-biz/test#71]
Выполнил задание :)

- [x] Ссылка на сайт: http://amariq.16mb.com;
- [x] Ссылка на **код плагина**: http://pastebin.com/tGAjzh2P;

А так как весь функционал у меня реализован в коде темы, и плагин лишь использует функции темы, если они доступны, то вот ссылка на **код темы**: http://pastebin.com/TKZTkmaJ.
- [x] Скриншот с шаблоном страницы фильма: http://prntscr.com/8083pk.

На всякий случай, **[вот ссылка](https://drive.google.com/folderview?id=0By8L_azp0nONcllWUmdxSnI0T3M)** на папку Google Drive со всеми файлами задания.

Ну и последнее: Pull request для CasePress **Issue 18**: https://github.com/systemo-biz/casepress/pull/36.

**Comment by yumashev** [comment]
Круто! Напиши свой email

**Comment by amariq** [comment]
amariq@yandex.com =)
