### ISSUE TITLE
Ход работы

### ISSUE THREAD

**Issue by HjortRus** [systemo-biz/test#79]
Добрый день.Поздно заметил тестовое задание на почте.Я в процессе(isvarun@mail.ru)
Сайт: http://infrastudio.ru/ 
Хостинг свой:Majordomo
1. Есть
2. Есть
http://pastebin.com/HSpV6rh9
Делал через фильтр.
2.4 В процессе
3. Есть

Код шаблона:
![default](https://cloud.githubusercontent.com/assets/15354431/10816552/68f7bd90-7e55-11e5-9b94-4ab9b09c8b75.JPG)

**Comment by yumashev** [comment]
Код шаблона - ошибка. Ты поправил шаблон всех одиночных постов. А надо только для фильмов. Внимательней читай инструкцию про иерархию шаблонов.

**Comment by HjortRus** [comment]
Вот шорткод мучаю:
function lastfilm(){
global $post; 
$args = array('posts_per_page' => 5, 'order'=> 'ASC', 'orderby' => 'post_date', category => 38); 
$posts = get_posts( $args );
foreach( $posts as $post ){ setup_postdata($post);

}
wp_reset_postdata(); 

}
add_shortcode('shortcode', 'lastfilm');

Почему то в статье не цепляет его, если пишу [shortcode]

**Comment by yumashev** [comment]
птм что шорткод возвращает данные. а не печатает.

то как ты написал код внутри функции допустимо внутри шаблона. но не допустимо внутри функции.
внутри функции нужно делать возврат = return

а чтобы результат обработки мог вернуться через переменную, его надо запаковать в переменную, а для этого надо использовать механизм ob_start

**Comment by HjortRus** [comment]
Как-то так?
function lastfilm($posts){
global $post; 
$args = array('posts_per_page' => 5, 'order'=> 'ASC', 'orderby' => 'post_date', category => 38); 
$posts = get_posts( $args );
return $posts;
}
ob_start(lastfilm);
add_shortcode('shortcode', 'lastfilm');

По идее где-то необходимо еще ob_end_flush() вставить.
Вроде бы сама функция верная.

**Comment by HjortRus** [comment]
Или так:
ob_start(lastfilm() use ($posts) {
global $post; 
$args = array('posts_per_page' => 5, 'order'=> 'ASC', 'orderby' => 'post_date', category => 38); 
$posts = get_posts( $args );
return $posts;
add_shortcode('shortcode', 'lastfilm');
});
ob_end_flush()

Совсем забыл php :(

**Comment by yumashev** [comment]
жестко. других вариантов нет? почитать инструкции не получается?
