### ISSUE TITLE
Проба задания

### ISSUE THREAD

**Issue by hardwalker2010** [systemo-biz/test#81]
Доброго дня.

1. Ссылка на сайт: http://hardwalker.890m.com/

2. Код плагина: http://pastebin.com/4kMncLHk

3. Скриншот (или нужно просто-ссылкой?):
![screen01](https://cloud.githubusercontent.com/assets/16043590/11437406/4069794c-950f-11e5-9c3a-b5f46e4b2e73.jpg)

**Comment by yumashev** [comment]
вроде ок, напиши почту

**Comment by hardwalker2010** [comment]
почта: hardwalker2010@gmail.com

**Comment by yumashev** [comment]
ок, отписал на почту
