### ISSUE TITLE
По файлу functions.php

### ISSUE THREAD

**Issue by Esionhi** [systemo-biz/test#83]
В целом разобрался, однако не понял, как работает файл functions.php в дочерней теме.
Получается, что в него можно писать функции и оформлять хуки, шорткоды с помощью add_action($a, $b), здесь в $a название функции, куда вставить хук, в $b название моей функции; и add_shortcode($a, $b), в $a название, по которому вызывается шорткод, в $b вызываемый код.
Например, если такой файл написать: http://pastebin.com/earJbYKt, то ни хуки, ни шорткоды вне его не работают. Вызываю, например, в content.php через [last5] прям в коде.
Вот чувствую, что что-то не так оформляю)

**Comment by yumashev** [comment]
не понятно что это
add_action('film_extra', 'film_extra_func');

**Comment by Esionhi** [comment]
Согласен, посмотрел на это после того, как отдохнул, понял ошибку) Мы ж с контентом работаем
