### ISSUE TITLE
Тестовое задание

### ISSUE THREAD

**Issue by tanzoor** [systemo-biz/test#86]
Добрый день!

Вроде все сделал, проверьте пожалуйста.

Сайт : https://systemo-tanzoor.rhcloud.com/
Плагин : http://pastebin.com/y9k86Nf3
Шаблон : https://yadi.sk/i/NypOjuJCmUPne

Я использовал тему WPBSS, в связи с чем возникли некоторые сложности.

1) В этой теме в шаблоне архива постов используется вывод контента поста через `the_excerpt()`, поэтому в коде плагина пришлось использовать фильтр `add_filter( 'the_excerpt', 'display_movie_meta' );`. Но тогда код плагина не работал в других темах, где используется вывод через `the_content()`. Поскольку плагин должен быть независимым от темы и от наличия цитаты, то пришло решение использовать еще и `add_filter( 'the_content', 'display_movie_meta' );`.
 
Я пытался в коде функции определять наличие цитаты и соответственно использовать только фильтр контента, то мне это не удалось, возможно из-за того, что `the_excerpt()` сам генерирует цитату в случае ее отсутствия. В итоге я решил отказаться от фильтра цитаты и просто создать свой шаблон в дочерней теме с `the_content()`.

И сейчас получилось, что в архивах постов доп. информация выводится, а на страницах таксономий выводится неправильно (https://systemo-tanzoor.rhcloud.com/genre/adventure/), потому что там используется обычный шаблон с `the_excerpt()`. Видимо, можно создать еще один свой шаблон для таких случаев, но мне кажется, я что-то делаю не так.

Нормально ли применять одновременно одну функцию к двум фильтрам типа `add_filter( 'the_excerpt', '...' );` и `add_filter( 'the_content', '...' );`? Кажется, что нужно в коде функции предусматривать разные варианты и использовать только один фильтр.

2) Я удивился, что в коде темы стили бутстрапа подключаются после стилей темы, при этом почти полностью их заменяя. Разве это не нарушает смысл использования бутстрапа, чтобы на основе его стилей делать свои модификации?

В итоге чтобы добавить свои стили, которые будут изменять текущие, просто сделал еще один css-файл и подключил его в экшене с большим приоритетом.

3) Мне не удалось нормально склонять месяцы в дате выхода фильма. Если я использовал формат даты "dd MM yy", то в русской локали выводилось "02 Апрель 2000". Надо было писать свою функцию для изменения названия месяца или есть более простой способ?

**Comment by yumashev** [comment]
1. ок, хороший показатель интеллекта )
2. по ошибке ок, спасибо. поправим. пока вроде не мешала.
3. можно так расставить поля что обойтись без склонений. либо в инете есть куча готовых решений которые это позволяют делать. но такие требования редко встречаются.

черкни тут email

**Comment by tanzoor** [comment]
tanzoor@gmail.com

**Comment by yumashev** [comment]
ок отписал на почту
