### ISSUE TITLE
Вопрос по ТЗ: Застрял с плагином 

### ISSUE THREAD

**Issue by HermitKermit** [systemo-biz/test#88]
Привет!  
Собственно, застрял с плагином. 
Код возвращает только значения полей (стоимость, дата) без всякого форматирования. И не возвращает таксономии (http://test-wpbss.rhcloud.com/movies/).

```php
<?php
/*
Plugin Name: Kbss movies meta
Description: Выводит meta-данные ( Cтоимость сеанса, дата выхода ) и таксаномии ( Жанры, страна ) для страниц с post_type = movies.
Author: Dmitry B.
*/

function display_movies_meta_kbss($content)

{
	
    if ( !is_single() && get_post_type() == 'movies' ) 
	
	{
		
		$post_id = get_the_ID();
		$countrys = get_the_term_list( $post_id, 'countrys');
		$genre = get_the_term_list( $post_id, 'genre');
		$price = the_field( 'seance_cost' );
		$release = the_field( 'release_date' );

		$movies_meta = 
		
			'<div class="row row-movies-meta"> 
			
				<div class="col-md-6">
					<span class="glyphicon glyphicon glyphicon glyphicon glyphicon-globe" aria-hidden="true"></span> 
					'.$countrys.'</a>
				</div>
				
				<div class="col-md-6">
					<span class="label label-primary"><span class="glyphicon glyphicon glyphicon glyphicon-rub" aria-hidden="true"></span>'.$price.'</span>
				</div>
				
				<div class="col-md-6">
					<span class="glyphicon glyphicon glyphicon glyphicon-film" aria-hidden="true"></span> 
					<a href="'.$genre.'</a>
				</div>
				
				<div class="col-md-6">
					<span class="label label-primary"><span class="glyphicon glyphicon glyphicon-hand-right" aria-hidden="true"></span>'.$release.'</span>
				</div>
				
			</div>'
			
        ;
 
        return $content . $movies_meta;
		
    } else {
		
        return $content;
		
    }
	
}

add_action("the_content", "display_movies_meta_kbss");

?>
```
Поможете ? Ошибка наверняка очевидная, но я ее не вижу )

**Comment by VitoK72** [comment]
Привет, http://wp-kama.ru/function/get_the_term_list  3, 4 и 5 параметр обязательны, хотя бы пустыми быть должны. ID поста лучше поучать так $post->ID нет лишних обращений к функциям.

**Comment by HermitKermit** [comment]
Да уж, это жесть :')  html./
Но проблема с форматированием в другом чем-то, 
У меня даже такой код выводит только test (никакого оформления):
```php
<?php
/*
Plugin Name: Kbss movies meta
Description: Выводит meta-данные ( Cтоимость сеанса, дата выхода ) и таксаномии ( Жанры, страна ) для страниц с post_type = movies.
Author: Dmitry B.
*/

function display_movies_meta_kbss($content)

{
	
    if ( !is_single() && get_post_type() == 'movies' ) 
	
	{
		
       

		$movies_meta = 
		
			"
			<div>
				<span class='test'>Test</span>
			</div>
			"
        ;
 
        return $movies_meta.$content;
		
    } else {
		
        return $content;
		
    }
	
}

add_action("the_content", "display_movies_meta_kbss");

?>
```
Может быть я как-то не так пытаюсь вывести и система их загоняет в какой-нибудь strip_tags ?

По поводу параметров get_the_term_list я в кодексе смотрел и там было написано optional,
(https://codex.wordpress.org/Function_Reference/get_the_term_list) и не стал их указывать, а оказывается они обязательные, как быть))

**Comment by HermitKermit** [comment]
Частично решено:
Заменил add_action("the_content"... на фильтр the_excerpt. Осталось поправить вывод из полей. На пути к успеху)

**Comment by HermitKermit** [comment]
Все получилось) Спасибо

**Comment by VitoK72** [comment]
Может они и не обязательные, но у меня без них почему то тоже никогда не работает. Советую простые функции на каме смотреть, там с примерами и на русском. Правда некоторые отсутствуют. Продолжай в том же духе! Успехов!)

**Comment by HermitKermit** [comment]
Спасибо, буду там. Кстати созрел вопрос по поводу add_action / add_filter. Я как понял по функционалу они идентичны, когда какую функции целесообразнее использовать? 
Читал, что для читаемости кода если добавляешь в вывод новые данные лучше использовать action, а если видоизменяешь изначальные - filter. Но окончательного понимания нет)

**Comment by VitoK72** [comment]
Тут такое дело получается, в программной части они абсолютно идентичны, и the_content это кстати тоже фильтр, а не событие. Я тоже долгое время не понимал разницы, потом нашел такую статью http://wp-kama.ru/id_6680/kak-rabotayut-huki-v-wordpress-filtry-i-sobytiya.html тут все довольно ясно описано еще и с примерами. Тем не менее, если останутся вопросы, задавай, на все ответим, просто я не вижу смысла писать новую статью, если есть замечательный материал.

**Comment by HermitKermit** [comment]
Да, статья хорошая, спасибо )
