### ISSUE TITLE
Вопросы по тестовому заданию

### ISSUE THREAD

**Issue by fastunov** [systemo-biz/test#89]
По части 1.

1) Как сделать так, чтобы ссылка на пост формировалась с транслитерацией? На скриншоте красной стрелкой отмечено то, что напрягает http://joxi.ru/8AnppgSqo6BDmO

2) Как сделать так, чтобы при вводе таксономии во время создания новой записи Фильм можно было выбирать ранее введенные значения?

**Comment by fastunov** [comment]
По части 2.

По отладке кода плагина.

Как наилучшим образом настроить отладку кода WP? Чтобы можно было из функции вывести значение переменной и при этом не рушить вывод сайта?

Настройку как рекомендуется  https://codex.wordpress.org/Debugging_in_WordPress сделал. В debug.log валятся предупреждения, но нужного функционала не получил.

**Comment by VitoK72** [comment]
Первая часть 
1)плагин rus to lat или подобное.
2) там и так можно, выбери вкладку не "Часто используемые" а "все". и будет счастье.
Вторая часть.
ну например так http://pastebin.com/izZmLdMn либо обьясни подробнее чего хочешь. Отвечу подробнее, а то вопрос не совсем понял.

**Comment by fastunov** [comment]
Вот похоже на то, чего хочется - https://www.kobzarev.com/programming/php-console.html
Буду пробовать.

**Comment by VitoK72** [comment]
а зачем тебе вообще такой функционал сейчас? Ты слишком усложняешь, тут плагин то простяцкий, один хук и пара функций.

**Comment by fastunov** [comment]
Интересно в кишках Wordpress покопаться. Я учусь параллельно, читаю про функции, хочется попробовать разные способы. Сроков-то нет - можно и углубиться.

**Comment by VitoK72** [comment]
углубляться то нужно постепенно) смысл учиться этому сейчас, если еще нет знаний на выполнение таких задач, где это может пригодится.

**Comment by fastunov** [comment]
Здравствуйте.

Прочитал про рекомендацию отказаться от использования @import для CSS в WordPress http://wpcraft.ru/ne-stoit-ispolzovat-import-s-css-v-wordpress/

А как тогда с дочерними темами работать?

**Comment by Grimm96** [comment]
Здравствуйте.

Столкнулся с проблемой при создании дочерней темы на примере темы Unite. В стиле прописал импорт "@import url('../unite/style.css');", но тему WP так и не видит. Пишет, что "Следующие темы установлены, однако являются неполными. Тема должна иметь таблицу стилей и шаблон.". Версия WP 4.4.2.
