### ISSUE TITLE
Закончил ТЗ 

### ISSUE THREAD

**Issue by HermitKermit** [systemo-biz/test#90]
Обязательную часть, точнее.

1. Сайт: http://test-wpbss.rhcloud.com/
2. Код плагина: http://pastebin.com/CybDbCiL
3. Скрин кода страницы:

![image](https://cloud.githubusercontent.com/assets/12055205/12520525/2a7d4230-c156-11e5-993f-df44e481fd03.png)

**Comment by yumashev** [comment]
закрыта авторизация на сайт

**Comment by HermitKermit** [comment]
Сейчас сайт доступен

**Comment by HermitKermit** [comment]
Гляните? )

**Comment by yumashev** [comment]
да все ок
