### ISSUE TITLE
Выполненное задание

### ISSUE THREAD

**Issue by Petro-1** [systemo-biz/test#91]
Добрый день! Сделал задание. 
1. http://terin.hol.es/
2. http://pastebin.com/GXVM5j3L
3. http://take.ms/xa932

**Comment by yumashev** [comment]
я так понял ты рещил поломать нам весь процесс стажировки, истребив все задачи для стажеров )))

давай прекратим этот беспредел ))

напиши свою почту.

**Comment by Petro-1** [comment]
Просто хочу что-то делать!) kopivan@mail.ru

**Comment by yumashev** [comment]
Ответил на почту.
