### ISSUE TITLE
Тестовое задание

### ISSUE THREAD

**Issue by ellfoss** [systemo-biz/test#93]
Здравствуйте! Решил заняться изучением WordPress, чтобы пройти тестовое задание. Первый пункт вопросов не вызвал и прошел легко. Проблемы начались со второго пункта, а вместе с ними возникли и вопросы. После внесения в базу нескольких фильмов решил поинтересоваться, как же всё-таки отобразить все внесённые фильмы. Ведь по умолчанию выводятся простые записи, но никак не фильмы. Я создал новую страницу, на которой предполагаю выводить фильмы, прописал шаблон для этой страницы, подключил его, но он почему-то не отработал. Хотя всё делал по инструкции. Из папки темы 'unite' скопировал в папку с активной дочерней темой 'unite-child' файл index.php. Переименовал его в page-films.php. Добавил в начало файла запись

<?php
/*
Template Name: Список фильмов
*/

А также перед <?php if ( have_posts() ) : ?> вставил запись

$args = array(
   'post_type' => 'films',
   'publish' => true,
   'paged' => get_query_var('paged'),
   );
query_posts($args);

После этого при создании страницы в атрибутах появляется новый шаблон 'Список фильмов'. Я его выбираю, но со страницей ничего не происходит.
Но если все эти изменения проделать в самом файле index.php, то всё срабатывает, но на всех страницах, а не на одной нужной. Поэтому и возник вопрос: что я делаю не так? Как заставить шаблон отрабатывать на нужной странице? Может я вообще не в том направлении двигаюсь и всё делается гораздо проще?

**Comment by yumashev** [comment]
Сложно и не туда.
Если все верно сделано то фильмы будут отображаться без подкопотных кодописаний.
Не надо менять код, все и так работает. Главное внимательно читать что написано в инструкциях. Ну или на худой конец погуглить.

**Comment by ellfoss** [comment]
Продолжаю терзать Wordpress, а он, соответственно, терзает меня. Список фильмов по умолчанию так и не захотел выводиться, сделал через шаблон. Через хук по заданию добавил вывод дополнительной информации о фильме, всё отработало замечательно. Далее решил заняться шорткодом. Создал страницу, на которой собирался вывести 5 последних фильмов, прописал её в меню (пока не стал ставить на главную). Попробовал вывести - никакого результата, заголовок выводится, а текст страницы - нет. Попробовал создать шаблон для этой страницы, результат тот же, the_content() возвращает пустую строку. Пробовал вывести через костыль get_post(get_the_ID())->post_content. Выводится, но шорткод в этом случае не обрабатывается и просто выводится его название. Вот и вопрос: по какой причине может не работать the_content()?
На этом проблемы не закончились. Решил всё-таки эту страницу сделать главной. Как только это сделал, сразу же слетели шаблоны всех страниц и они стали показывать только стартовую запись WordPress. Никакие последующие ухищрения не смогли вернуть предыдущий наработанный функционал. Помогала только чистая установка WordPress. Неужели я настолько криворукий? Или действительно в Wordpress есть ошибки? А может я просто не ту версию скачал? Брал вот отсюда: https://ru.wordpress.org/

**Comment by ellfoss** [comment]
Попробовал поставить другую версию Wordpress, ошибка осталась. Кстати, если поменять тему, а потом вернуть предыдущую, то шаблоны страниц тоже слетают. Создание новой страницы и применение к ней существующего шаблона тоже результатов не даёт - шаблоны просто не применяются. Я в полной растерянности... Куда копать дальше? Может надо сервер дополнительно настраивать? Хотя и на локале, и на хостинге сайт ведёт себя одинаково, но на хостинге мне никто не даст менять настройки.

**Comment by VitoK72** [comment]
Ох как все запутанно, я думаю тебе стоит начать сначала с того момента как внес фльмы, а выводятся они просто, если имя кастомного типа записи у тебя films то вывести их можно так http://твой_сайт.ru/films предварительно настроив чпу вот таким образом http://prntscr.com/a9c8o8

**Comment by ellfoss** [comment]
В том и дело, что даже так не работает. Настройка постоянных ссылок на название записи у меня  сначала была сделана. Удалил все созданные страницы (из корзины тоже), попробовал вывести через http://мой_сайт.ru/films - та же проблема, выводится только первоначальная запись, но не фильмы. Всё хорошо работает именно до момента смены темы или присвоения главной страницы. Обратные действия не приводят к предыдущему результату, всё конкретно ломается. Мне, наверное, тестером надо работать, чтобы ронять даже надёжные системы :)

**Comment by ellfoss** [comment]
C the_content() разобрался, просто в моём плагине возврат результата был только при выполнении условий проверки. Перенёс return на строчку ниже, всё заработало. А вот с отображением на главной странице статической так и не получается - сбрасываются шаблоны. Стал делать умнее, чтобы каждый раз не переустанавливать WordPress, сделал бэкап базы WordPress до применения настроек с главной страницей. При восстановлении бэкапа, восстанавливается и работоспособность сайта. Буду дальше пытаться разобраться с этой проблемой.

**Comment by VitoK72** [comment]
Тут 15-30 минут задание делается, откуда столько проблем, не понимаю, зачем столько действий, тоже не понимаю, покажи настройки пользовательского типа записи, когда создавал ее, там есть настройки, покажи их.

**Comment by ellfoss** [comment]
Настройки не менял, оставлял по-умолчанию. http://den.kashnikoff.ru/screen/screen.jpg

**Comment by yumashev** [comment]
Has archive дб True. Иначе механизм архива не работает.

**Comment by ellfoss** [comment]
Спасибо за ответы. В принципе всё получилось. Но возникла проблема другого характера. Сайт pastebin.com - доступ к ресурсу ограничен, хотя днём он ещё нормально работал, не понятно, за что его заблокировали. Но это не беда, у нас же есть аналог - pastebin.ru, вот им и воспользовался :)
1. http://den.kashnikoff.ru/films/
2. http://pastebin.ru/SmaTH8Ar
3. http://den.kashnikoff.ru/screen/template.jpg

**Comment by yumashev** [comment]
Все ок, напиши свою электропочту

**Comment by ellfoss** [comment]
ellfoss@mail.ru

**Comment by yumashev** [comment]
написал
