### ISSUE TITLE
Тестовое задание

### ISSUE THREAD

**Issue by romale1980** [systemo-biz/test#94]
Доброго времени суток.
Уперся и никак не могу понять, почему ссылки с добавленными фильмами не действительны...
"Oops! That page can’t be found".
Установил расширение Custom Post Type Maker и решил проверить... Результат описал выше...

**Comment by yumashev** [comment]
нужен снимок страницы настроек типа поста

**Comment by romale1980** [comment]
https://yadi.sk/i/mOdcHF6Iq8ADV
https://yadi.sk/i/lzGv8X_Qq8AE7
https://yadi.sk/i/7Guyo69Iq8AEk
https://yadi.sk/i/7zeIxUlVq8AFX

**Comment by romale1980** [comment]
2016-03-13 5:52 GMT+03:00 Anatoly Yumashev <notifications@github.com>:

**Comment by romale1980** [comment]
Ссылки теперь работают... Единственное что не понятно, почему это происходит не сразу, а по истечению N-ного промежутка времени...

**Comment by romale1980** [comment]
нет... всё-таки проблема с новыми страницами осталась...
Готово всё, но не могу выложить на проверку из-за невозможности просмотра страниц находящихся в статусе "Опубликовано" (в статусе "Ожидает утверждения" их можно просмотреть)...

**Comment by yumashev** [comment]
тут суть вопроса не ясна. судя по параметрам все должно работать.
если не работает то нужен пример ссылки на пост и доступ в консоль.

**Comment by romale1980** [comment]
Я уже решил этот вопрос для себя. Проблемой оказалось имя таксономии year.
После изменения постоянные ссылки работают.
