### ISSUE TITLE
На проверку

### ISSUE THREAD

**Issue by romale1980** [systemo-biz/test#95]
На проверку...

1. http://test1234.kl.com.ua/
2. http://pastebin.com/uexLh8Fd
3. https://www.monosnap.com/file/kMVsyoC8KwFZtJnfRNVrD1H9uD6KcE
https://www.monosnap.com/file/4IqJezUoASMI1WlrhVgrmZKeMMqSjb

**Comment by romale1980** [comment]
Немного подправил...

1. http://movies.zzz.com.ua/
2. http://pastebin.com/uexLh8Fd
3. 
![function1](https://cloud.githubusercontent.com/assets/13920623/13792993/aeb6f874-eb05-11e5-8f36-2fb008980c9e.PNG)
![content-single](https://cloud.githubusercontent.com/assets/13920623/13792998/b91155f8-eb05-11e5-982a-df52d27518c9.PNG)

**Comment by yumashev** [comment]
тут http://test1234.kl.com.ua/?post_type=movies
верстка кривенькая. можно было бы и получше сделать.
отключены постоянные ссылки. это тоже плохо.
главная страница выдает ошибку.
в остальном похоже на правду и как бы работает.

попробуй исправить так чтобы сайт стал аккуратней и не походил на обломки крушения метеорита. покажи что есть аккуратность и чувство верстки. выжми максимум из своих знаний.

покажи что получилось и думаю перейдем к след шагам.

**Comment by romale1980** [comment]
Поправил... Проверьте
1. http://test1234.kl.com.ua/
2. http://pastebin.com/jiyE0GKS
3.
![films210316](https://cloud.githubusercontent.com/assets/13920623/13923568/4509de50-ef92-11e5-9041-55cd8c234ec4.PNG)

**Comment by romale1980** [comment]
Ладно...
Всё-равно с самого начала сомневался в этой затее)))...
Спасибо за приглашение!..

**Comment by yumashev** [comment]
все ок.
напиши свою почту.

**Comment by romale1980** [comment]
romale1980@gmail.com

**Comment by yumashev** [comment]
Отписал на почту.
