### ISSUE TITLE
Вопросы о сроках и формулировке задания.

### ISSUE THREAD

**Issue by Galtozar** [systemo-biz/test#96]
Доброго времени суток. Возникла парочка вопросов.

1. Есть ли ограничение по времени для выполнения тестового задания? Ибо раньше не имел опыта работы с WordPress'ом и хотелось бы чуть подольше покопаться в документации и попробовать пореализовывать что-то ещё.
2. Проблем с выводом мета данных для поста не возникло, но остался непонятен пункт 2.2. Что именно нужно сделать при помощи шаблона? 
Ведь по сути в пункте 2.1, создав хук я и так вывожу нужную информацию на странице с отдельным постом. Или же мне нужно просто реализовать "второй способ", дабы посмотреть, как ведётся работа с шаблонами?(Пока писал вопрос, понял для чего, и, перечитав задание полностью убедился окончательно =), удалять не буду).

С остальным проблем не возникло. Ожидаю ответов, спасибо.

**Comment by yumashev** [comment]
Сроков нет. Каждый сам решает когда ему это нужно.
Смысл этого задания не в результате. А в том чтобы показать какими методами работы владеет человек. Потому что в бою нужны разные методы работы.

**Comment by Galtozar** [comment]
@yumashev, спасибо)
