### ISSUE TITLE
Вопрос по ТЗ: помощь, подсказки и поддержка

### ISSUE THREAD

**Issue by romale1980** [systemo-biz/test#97]
Здравствуйте. 
У меня вопрос по поводу вопросов, поддержки и т.д....(о чем так хорошо написано в ТЗ)

Скажите [выполненное задание без ответа](https://github.com/systemo-biz/test/issues/95) и [оставшиеся вопросы](https://github.com/systemo-biz/test/issues/94) (хотя я уже решил проблему) можно понимать уже как "НЕТ" или игнорирование? Ответьте хоть что-нибудь.

P.S. Просто не понятно, почему игнорируете.

Спасибо.

**Comment by yumashev** [comment]
Не игнорируем. По мере возможности отвечаю. Сейчас очередной аврал словил и потому торможу. Как только доберусь, сразу гляну и отвечу.
