### ISSUE TITLE
На проверку.

### ISSUE THREAD

**Issue by Galtozar** [systemo-biz/test#98]
Доброго времени суток.

1. [Сайт](http://moviessys.hol.es/)
2. [Код плагина](http://pastebin.com/9636pcR3)
3. Скриншоты шаблона:
![first](https://cloud.githubusercontent.com/assets/14139502/14068104/5410b1c8-f481-11e5-95c7-4aeae2825a58.png)
![second](https://cloud.githubusercontent.com/assets/14139502/14068110/91c85b2e-f481-11e5-977e-00030910ca0a.png)

С нетерпением жду ответа.

**Comment by yumashev** [comment]
не плохая подорка фильмов, я аж залип ))
напиши адрес почты.

**Comment by Galtozar** [comment]
Что есть, то есть :)
galtozar@gmail.com

**Comment by yumashev** [comment]
Отписал в почту.
